[package]
name = "nio-server"
version = "0.1.0"
edition = "2024"

[dependencies]
nio = { workspace = true }
tokio = { version = "1", features = [
    "io-util",
] } # Doesn't compile with tokio from git for some reason
config = { path = "../config" }
