[workspace]

members = [
    "monoio-server",
    "tokio-server",
    "glommio-server",

    "client",

    "config"
]

[workspace.dependencies]
monoio = { git = "https://github.com/bytedance/monoio" }

[profile.release]
lto = true
debug = false
overflow-checks = false
